version: "3.9"

services:
  backend:
    build: ./backend
    container_name: chatbot_backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: chatbot_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: chatbot_nginx
    ports:
      - "10000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend